version: "3.8"

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    container_name: postgres_db
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: